Still buggy. Example error:
Error CS1503 Argument 8: cannot convert from 'System.Collections.Generic.List<int>' to 'int' EddiJournalMonitor C:\Users\Brian\Source\Repos\EliteDangerousDataProvider\JournalMonitor\JournalMonitor.cs 1702 Active